version: '3'
services:
  Usa_South:
    image: mongo
    container_name: Usa_South  #shard-03-node-a
    command: mongod --port 27017  --shardsvr --replSet "Stephanie" --bind_ip_all
    ports:
      - 27126:27026
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.12

  Usa_West:
    image: mongo
    container_name: Usa_West #shard-03-node-b
    command: mongod --port 27017  --shardsvr --replSet "Stephanie" --bind_ip_all
    ports:
      - 27127:27027
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.13
    
  Usa_East:
    image: mongo
    container_name: Usa_East #shard-03-node-c
    command: mongod --port 27017  --shardsvr --replSet "Stephanie" --bind_ip_all
    ports:
      - 27128:27028
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.14

      
networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27