version: '3'
services:
  CR_Sur:
    image: mongo
    container_name: CR_Sur #shard-02-node-a
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27123:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.9

  CR_Oeste:
    image: mongo
    container_name: CR_Oeste #shard-02-node-b
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27124:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.10

  CR_Este:
    image: mongo
    container_name: "CR_Este" #shard-02-node-c
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27125:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.11

  ## Arbiters
  CR_arb:
    image: mongo
    container_name: Mar_arb
    command: mongod --port 27017 --replSet "CompuMario" --bind_ip_all --oplogSize 64
    ports:
      - 27134:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.19

networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27