version: '3'
services:
  CR_Sur:
    image: mongo
    container_name: CR_Sur #shard-02-node-a
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27123:27017
    networks:
      OurNetwork:
        ipv4_address: 25.3.224.2

  CR_Oeste:
    image: mongo
    container_name: CR_Oeste #shard-02-node-b
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27124:27017
    networks:
      OurNetwork:
        ipv4_address: 25.3.224.3

  CR_Este:
    image: mongo
    container_name: "CR_Este" #shard-02-node-c
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27125:27017
    networks:
      OurNetwork:
        ipv4_address: 25.3.224.4
    
networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 25.3.224.0/27