version: '3'
services:
  
  
    
  ## Shard Servers
  Gm_Sur:
    image: mongo
    container_name: Gm_Sur  #shard-03-node-a
    command: mongod --port 27017  --shardsvr --replSet "Camilo" --bind_ip_all
    ports:
      - 27130:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.15
    
  Gm_Oeste:
    image: mongo
    container_name: Gm_Oeste #shard-03-node-b
    command: mongod --port 27017  --shardsvr --replSet "Camilo" --bind_ip_all
    ports:
      - 27131:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.16
  Gm_Este:
    image: mongo
    container_name: Gm_Este #shard-03-node-c
    command: mongod --port 27017  --shardsvr --replSet "Camilo" --bind_ip_all
    ports:
      - 27132:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.17    


      
  Gm_Arb:
    image: mongo
    container_name: Gm_Arb
    command: mongod --port 27017 --replSet "Camilo" --bind_ip_all --oplogSize 64
    ports:
      - 27136:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.21

networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27