version: '3'
services:
  ## Shards
  Mex_Sur:
    image: mongo
    container_name: Mex_Sur #shard-01-node-a
    command: mongod --port 27017  --shardsvr --replSet "Raulis" --bind_ip_all
    ports:
      - 27120:27017
    networks:
      OurNetwork:
        ipv4_address: 25.19.99.56

  Mex_oeste:
    image: mongo
    container_name: Mex_oeste #shard-01-node-b
    command: mongod --port 27017  --shardsvr --replSet "Raulis" --bind_ip_all
    ports:
      - 27121:27017
    networks:
      OurNetwork:
        ipv4_address: 25.19.99.57

  Mex_Este:
    image: mongo
    container_name: Mex_Este #shard-01-node-c
    command: mongod --port 27017  --shardsvr --replSet "Raulis" --bind_ip_all
    ports:
      - 27122:27017
    networks:
      OurNetwork:
        ipv4_address: 25.19.99.58
    
networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 25.19.99.53/27