version: '3'
services:

## Router
  Router_1:
    image: mongo
    container_name: Router_1
    command: mongos --port 27017  --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27027:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.2
    restart: always
    
  Router_2:
    image: mongo
    container_name: Router_2
    command: mongos --port 27017  --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27007:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.3
    restart: always
    links:
      - Router_1

## Config Servers
  Config_1:
    image: mongo
    container_name: Config_1
    command: mongod --port 27017  --configsvr --replSet rs-config-server 
    ports:
      - 27037:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.4
    restart: always

  Config_2:
    image: mongo
    container_name: Config_2
    command: mongod --port 27017  --configsvr --replSet rs-config-server
    ports:
      - 27047:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.5
    restart: always
    links:
      - Config_1

## Shards
  Mex_Sur:
    image: mongo
    container_name: Mex_Sur #shard-01-node-a
    command: mongod --port 27017  --shardsvr --replSet "Raulis"
    ports:
      - 27117:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.7
    restart: always
    links:
      - Mex_oeste #shard01-b
      - Mex_Este #shard01-c

  Mex_oeste:
    image: mongo
    container_name: Mex_oeste #shard-01-node-b
    command: mongod --port 27017  --shardsvr --replSet "Raulis"
    ports:
      - 27118:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.8
    restart: always

  Mex_Este:
    image: mongo
    container_name: Mex_Este #shard-01-node-c
    command: mongod --port 27017  --shardsvr --replSet "Raulis"
    ports:
      - 27119:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.9
    restart: always

  CR_Sur:
    image: mongo
    container_name: CR_Sur #shard-02-node-a
    command: mongod --port 27017  --shardsvr --replSet "CompuMario"
    ports:
      - 27120:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.10
    restart: always
    links:
      - CR_Oeste #shard02-b
      - CR_Este #shard02-c

  CR_Oeste:
    image: mongo
    container_name: CR_Oeste #shard-02-node-b
    command: mongod --port 27017  --shardsvr --replSet "CompuMario"
    ports:
      - 27121:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.11
    restart: always

  CR_Este:
    image: mongo
    container_name: "CR_Este" #shard-02-node-c
    command: mongod --port 27017  --shardsvr --replSet "CompuMario"
    ports:
      - 27122:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.12
    restart: always

  Usa_South:
    image: mongo
    container_name: Usa_South  #shard-03-node-a
    command: mongod --port 27017  --shardsvr --replSet "Stephanie"
    ports:
      - 27123:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.13
    restart: always
    links:
      - Usa_West #shard03-b
      - Usa_East #shard03-c

  Usa_West:
    image: mongo
    container_name: Usa_West #shard-03-node-b
    command: mongod --port 27017  --shardsvr --replSet "Stephanie"
    ports:
      - 27124:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.14
    restart: always

  Usa_East:
    image: mongo
    container_name: Usa_East #shard-03-node-c
    command: mongod --port 27017  --shardsvr --replSet "Stephanie"
    ports:
      - 27125:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.15
    restart: always

  Gm_Sur:
    image: mongo
    container_name: Gm_Sur  #shard-03-node-a
    command: mongod --port 27017  --shardsvr --replSet "Camilo"
    ports:
      - 27126:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.16
    restart: always
    links:
      - Gm_Oeste #shard04-b
      - Gm_Este #shard04-c

  Gm_Oeste:
    image: mongo
    container_name: Gm_Oeste #shard-03-node-b
    command: mongod --port 27017  --shardsvr --replSet "Camilo"
    ports:
      - 27127:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.17
    restart: always

  Gm_Este:
    image: mongo
    container_name: Gm_Este #shard-03-node-c
    command: mongod --port 27017  --shardsvr --replSet "Camilo"
    ports:
      - 27128:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.18
    restart: always

#  #create a network

networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27
#  RaulisNet:
#    driver: bridge
#    ipv4_address: 25.19.99.53
#
#  MarioNet:
#    driver: bridge
#    ipv4_address: 25.3.224.0
#
#  StephanieNet:
#    driver: bridge
#    ipv4_address: 25.3.188.46
#  
#  CamiloNet:
#    driver: bridge
#    ipv4_address: 25.3.189.113

