version: '3'
services:
  
  ## Router
  Router_1:
    image: mongo
    container_name: Router_1
    command: mongos --port 27017  --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27027:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.2
    restart: always
  Router_2:
    image: mongo
    container_name: Router_2
    command: mongos --port 27018  --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27007:27018
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.3
    restart: always
  ## Config Servers
  Config_1:
    image: mongo
    container_name: Config_1
    command: mongod --port 27019  --configsvr --replSet rs-config-server # Falta Network
    ports:
      - 27037:27019
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.4
    restart: always
  Config_2:
    image: mongo
    container_name: Config_2
    command: mongod --port 27020  --configsvr --replSet rs-config-server
    ports:
      - 27047:27020
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.5
    restart: always
    
  ## Shard Servers
  Gm_Sur:
    image: mongo
    container_name: Gm_Sur  #shard-03-node-a
    command: mongod --port 27021  --shardsvr --replSet "Camilo"
    ports:
      - 27126:27021
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.16
    restart: always
    
  Gm_Oeste:
    image: mongo
    container_name: Gm_Oeste #shard-03-node-b
    command: mongod --port 27022  --shardsvr --replSet "Camilo"
    ports:
      - 27127:27022
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.17
    restart: always
  Gm_Este:
    image: mongo
    container_name: Gm_Este #shard-03-node-c
    command: mongod --port 27023  --shardsvr --replSet "Camilo"
    ports:
      - 27128:27023
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.18
    restart: always