version: '3'
services:
## Config Servers
  Config_1:
    image: mongo
    container_name: Config_1
    command: mongod --port 27017  --configsvr --replSet "configrs" --dbpath /data/configdb --bind_ip_all # Falta Network
    ports:
      - 27119:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.2

  Config_2:
    image: mongo
    container_name: Config_2
    command: mongod --port 27017  --configsvr --replSet "configrs" --dbpath /data/configdb --bind_ip_all
    ports:
      - 27120:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.3

  CR_Sur:
    image: mongo
    container_name: CR_Sur #shard-02-node-a
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27124:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.9

  CR_Oeste:
    image: mongo
    container_name: CR_Oeste #shard-02-node-b
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27125:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.10

  CR_Este:
    image: mongo
    container_name: "CR_Este" #shard-02-node-c
    command: mongod --port 27017  --shardsvr --replSet "CompuMario" --bind_ip_all
    ports:
      - 27126:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.11

  ## Router
  Router_1:
    image: mongo
    container_name: Router_1
    command: mongos --port 27017 --configdb configrs/Config_1:27017,Config_2:27017 --bind_ip_all
    ports:
      - 27017:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.4
    depends_on:
      - Config_1
      - Config_2
  Router_2:
    image: mongo
    container_name: Router_2
    command: mongos --port 27017 --configdb configrs/Config_1:27017,Config_2:27017 --bind_ip_all
    ports:
      - 27018:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.5
    depends_on:
      - Config_1
      - Config_2
      
  ## Arbiters
  CR_arb:
    image: mongo
    container_name: Mar_arb
    command: mongod --port 27017 --replSet "CompuMario" --bind_ip_all --oplogSize 64
    ports:
      - 27134:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.19

networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27