version: '3'
services:
  
  ## Config Servers
  Config_1:
    image: mongo
    container_name: Config_1
    command: mongod --port 27017  --configsvr --replSet "configrs" --dbpath /data/configdb --bind_ip_all # Falta Network
    ports:
      - 27118:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.2

  Config_2:
    image: mongo
    container_name: Config_2
    command: mongod --port 27017  --configsvr --replSet "configrs" --dbpath /data/configdb --bind_ip_all
    ports:
      - 27119:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.3
    
  ## Shard Servers
  Gm_Sur:
    image: mongo
    container_name: Gm_Sur  #shard-03-node-a
    command: mongod --port 27017  --shardsvr --replSet "Camilo" --bind_ip_all
    ports:
      - 27129:27027
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.15
    
  Gm_Oeste:
    image: mongo
    container_name: Gm_Oeste #shard-03-node-b
    command: mongod --port 27017  --shardsvr --replSet "Camilo" --bind_ip_all
    ports:
      - 27130:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.16
  Gm_Este:
    image: mongo
    container_name: Gm_Este #shard-03-node-c
    command: mongod --port 27017  --shardsvr --replSet "Camilo" --bind_ip_all
    ports:
      - 27131:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.17

  ## Router
  Router_1:
    image: mongo
    container_name: Router_1
    command: mongos --port 27017 --configdb configrs/Config_1:27017,Config_2:27017 --bind_ip_all
    ports:
      - 27017:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.4

  Router_2:
    image: mongo
    container_name: Router_2
    command: mongos --port 27017 --configdb configrs/Config_1:27017,Config_2:27017 --bind_ip_all
    ports:
      - 27018:27017
    networks:
      OurNetwork:
        ipv4_address: 10.0.0.5

networks:
  OurNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27