version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper-server
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka
    container_name: kafka-server
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./kafka-data:/bitnami/kafka/data

networks:
  kafka-network:
    driver: bridge